[package]
name = "scirs2-fft"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Fast Fourier Transform module for SciRS2"
license.workspace = true
repository.workspace = true
keywords = ["fft", "fourier", "scientific", "scipy", "numerical"]
categories = ["science", "mathematics", "algorithms"]

[features]
default = ["helper", "window", "parallel"]
helper = []
window = []
minimal = []
parallel = []

[dependencies]
# Core dependencies
ndarray.workspace = true
num-traits.workspace = true
num-complex.workspace = true
thiserror.workspace = true
scirs2-core = { workspace = true, features = ["simd", "parallel"] }
rayon.workspace = true

# FFT specific dependencies
rustfft.workspace = true
rand.workspace = true

[dev-dependencies]
approx.workspace = true
criterion.workspace = true
