[package]
name = "scirs2-signal"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Signal processing module for SciRS2"
license.workspace = true
repository.workspace = true
keywords = ["signal-processing", "filter", "scientific", "scipy", "numerical"]
categories = ["science", "mathematics", "algorithms"]

[dependencies]
# Core dependencies
scirs2-core.workspace = true
ndarray.workspace = true
num-traits.workspace = true
num-complex.workspace = true
thiserror.workspace = true

# Signal processing specific dependencies
rustfft.workspace = true
scirs2-fft.workspace = true
rand.workspace = true

[dev-dependencies]
approx.workspace = true
criterion.workspace = true
