[package]
name = "scirs2-neural"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Neural network building blocks module for SciRS2"
repository.workspace = true
keywords = ["neural-network", "deep-learning", "scientific", "ai", "machine-learning"]
categories = ["science", "mathematics", "algorithms", "ai"]

[dependencies]
# Core dependencies
scirs2-core = { workspace = true, optional = true }
scirs2-linalg = { workspace = true, optional = true }
scirs2-optimize = { workspace = true, optional = true }
scirs2-optim = { workspace = true, optional = true }
ndarray.workspace = true
ndarray-stats = { workspace = true }
num-integer.workspace = true
approx = { workspace = true }
num-traits = { workspace = true }
num-complex = { workspace = true }
thiserror.workspace = true
rand = { workspace = true }

# AI/ML specific dependencies
autograd.workspace = true
scirs2-autograd.workspace = true

# Future dependency for PandRS and NumRS with appropriate abstractions
# pandrs_wrapper = { path = "../wrappers/pandrs_wrapper", optional = true }
# numrs_wrapper = { path = "../wrappers/numrs_wrapper", optional = true }

[features]
default = []
full = ["core", "linalg", "optimize", "optim"]
core = ["dep:scirs2-core"]
linalg = ["dep:scirs2-linalg"] 
optimize = ["dep:scirs2-optimize"]
optim = ["dep:scirs2-optim"]

[[example]]
name = "autograd_example"
path = "examples/autograd_example.rs"