[package]
name = "scirs2-ndimage"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "N-dimensional image processing module for SciRS2"
repository.workspace = true
keywords = ["image", "processing", "scientific", "scipy", "numerical"]
categories = ["science", "mathematics", "algorithms"]

[dependencies]
# Core dependencies
scirs2-core = { workspace = true, features = ["simd", "validation", "parallel", "cache"] }
scirs2-interpolate.workspace = true
ndarray.workspace = true
num-traits.workspace = true
thiserror.workspace = true
ndarray-rand.workspace = true
approx.workspace = true
cached.workspace = true
# Use scirs2-core's modules instead of direct dependencies
# rayon.workspace = true
# wide.workspace = true  # Direct SIMD acceleration

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "rank_filter_bench"
path = "../benches/ndimage/rank_filter_bench.rs"
harness = false
