[package]
name = "scirs2-integrate"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Numerical integration module for SciRS2"
license.workspace = true
repository.workspace = true
keywords = ["integration", "quadrature", "scientific", "scipy", "numerical"]
categories = ["science", "mathematics", "algorithms"]

[dependencies]
# Core dependencies
scirs2-core.workspace = true
scirs2-linalg.workspace = true
ndarray.workspace = true
num-traits.workspace = true
num-complex.workspace = true
thiserror.workspace = true
rand.workspace = true
rand_distr.workspace = true
rand_core.workspace = true
libc.workspace = true
libm.workspace = true

[dev-dependencies]
approx.workspace = true
criterion.workspace = true

[[bench]]
name = "integrator_bench"
harness = false

[features]
default = []
simd = ["scirs2-core/simd"]
parallel = ["scirs2-core/parallel"]