[package]
name = "scirs2-special"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Special functions module for SciRS2"
license.workspace = true
repository.workspace = true
keywords = ["special-functions", "gamma", "scientific", "scipy", "numerical"]
categories = ["science", "mathematics", "algorithms"]

[dependencies]
# Core dependencies
ndarray.workspace = true
num-traits.workspace = true
num-complex.workspace = true
thiserror.workspace = true

[dev-dependencies]
approx.workspace = true
criterion.workspace = true
