[package]
name = "scirs2-stats"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Statistical functions module for SciRS2"
license.workspace = true
repository.workspace = true
keywords = ["statistics", "probability", "scientific", "scipy", "numerical"]
categories = ["science", "mathematics", "algorithms"]

[dependencies]
# Core dependencies
ndarray.workspace = true
num-traits.workspace = true
num-complex.workspace = true
thiserror.workspace = true
ndarray-linalg = { workspace = true, features = ["openblas-static"] }
scirs2-core = { version = "0.1.0-alpha.1", path = "../scirs2-core", features = ["validation", "parallel", "simd", "linalg", "openblas"] }

# Statistics specific dependencies
rand.workspace = true
rand_distr.workspace = true
rand_pcg.workspace = true
statrs.workspace = true

[dev-dependencies]
approx.workspace = true
criterion.workspace = true
